# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: upload jar
      run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v1
      with:
        name: lab-41-demo01-1.2-release.jar
        path: staging
    - name: GitHub Action for Dingtalk
      uses: cooperwu/action-dingtalk@v0.0.1
            action "Dingtalk notification" {
            uses = "cooperwu/action-dingtalk@master"
            secrets = ["DINGTALK_WEBHOOK"]
            }
